account/urls.py
from django.urls import path, include
from .account_views import views
from .students import views as s_views
from django.contrib.auth.views import LoginView, LogoutView
from account.utils.payme import PaymeView

app_name = 'account'

urlpatterns = [
    path('login/', views.login_view, name='log_in'),
    path('logout/', views.log_out, name='log_out'),
    path('signup/', views.register, name='sign_up'),
    path('verify/', views.verify, name='verify'),
    path('resend/', views.otp, name='resend'),

    path('teacher/edit/', views.user_update_view, name='teacher_edit'),

    # change
    path(
        "password_change/", views.PasswordChangeView.as_view(), name="password_change"
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset/", views.PasswordResetView.as_view(template_name='account/change/reset_password.html',
                                                            email_template_name='new/reset_password_email.html'),
         name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(template_name='account/change/reset_password_done.html'),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(template_name='account/change/reset_password_confirm.html'),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(template_name='account/change/reset_done.html'),
        name="password_reset_complete",
    ),

    path('enroll-course/', s_views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/', s_views.StudentCourseListView.as_view(), name='student_course_list'),
    # path('course/<slug:group_s>/<slug:course_s>/', s_views.StudentCourseDetailView.as_view(),
    #      name='student_course_detail'),
    path('course/<slug:group_s>/<slug:course_s>/', s_views.student_course_module_list, name='student_course_detail'),
    path('course/<pk>/<module_id>/', s_views.StudentCourseDetailView.as_view(), name='student_course_detail_module'),
    # path('profile/', views.dashboard_student, name='stdudent_dashboard'),

    path('profile/', s_views.StudentdDashboardView.as_view(), name='stdudent_dashboard'),
    path('profile/edit/', s_views.student_update_view, name='user_edit_profile'),
    path('payment_info/', s_views.StudentPaymentInfo.as_view(), name='payment_info'),

    # path('module/<slug:course_slug>/<int:pk>/', s_views.ModuleContentDetail.as_view(), name='module_detail'),
    path('module/<slug:course_slug>/<int:pk>/', s_views.ModuleDetailView.as_view(), name='module_detail'),

    # path('quiz/', include('students.quiz.urls')),
    path('sertificate/<uuid>/', s_views.ViewPDF.as_view(), name='sertificate'),
    path('payment', PaymeView.as_view(), name='payment'),
]

courses/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from courses.index_view import views as index

app_name = 'course'

urlpatterns = [
    path('', index.home_page, name='homepage'),
    path('course/', index.course_list_view, name='course_list'),

    path('subject/<slug:subject>/', index.CourseListView.as_view(),
         name='course_list_subject'),
    path('<slug:slug>/', index.CourseDetailView.as_view(), name='course_detail'),

    # dashboard urls
    path('course/manage/', include('courses.urls_manage')),
]

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL,
#                          document_root=settings.MEDIA_ROOT)

#urlpatterns += static(settings.STATIC_URL,
#                      document_root=settings.STATIC_ROOT)

edulive/urls.py
import random
import time
from django.views.static import serve

from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from account.models import CustomUser, Students
from get_sms import Getsms
from faker import Faker
from account.forms import RegisterUserForm
from django.http import HttpResponse
from get_sms import Getsms
from django.http import HttpResponse
#
# def create_user(request):
#     students = CustomUser.objects.all()[:100]

# for x in students:
#     Students.objects.create(user=x)
# fake = Faker()
# for x in range(1000):
#
#     name = fake.name()
#     if len(name.split(' '))==2:
#         username = str(name).split(' ')[0].lower()
#         phone_number = "99899000{:04d}".format(x)
#
#         data = {
#             'username': username,
#             'phone_number': phone_number,
#             'full_name': f"{name} {username.capitalize()}",
#             'email': fake.email(),
#             'password1': 'admin111',
#             'password2': 'admin111',
#         }
#         form = RegisterUserForm(data)
#         print(form.is_valid())
#         if form.is_valid():
#             print('valid')
#             form.save()
#             print('save')

# return redirect('course:homepage')
def send_s(request):
    login = 'Stable'
    password = '51v4N0y4R3N5rbcy122c'
    message = Getsms(login=login, password=password)
    phone = ['998997047646']
    result = message.send_message(phone_numbers=phone, text=f"sizning verifikatsiya kodingiz {123456}")
    return HttpResponse(result)
urlpatterns = [
    path('mvzona/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('news/', include('news.urls')),
    path('quiz/', include('quiz.urls')),
    path('create/', send_s),
    path('', include('courses.urls')),

    #path('__debug__/', include('debug_toolbar.urls')),
   #path('create/', sms_send, name='create')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),]

if settings.DEBUG:
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)

#urlpatterns += static(settings.MEDIA_URL,
#                      document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL,
#                      document_root=settings.STATIC_ROOT)
#

news/urls.py
from django.urls import path
from news.views import blog_news, blog_single_news, blog_search, offerta

app_name = 'news'

urlpatterns = [
    path('', blog_news, name='news'),
    path('<int:pk>/', blog_single_news, name='single_news'),
    path('search/', blog_search, name='search_news'),
    path('offerta/', offerta, name='offerta'),
]

quiz/urls.py
from django.urls import path
from quiz import views

app_name = 'quiz'

urlpatterns = [
    path('manage/quiz/list/', views.QuizListView.as_view(), name='quiz_list'),
    path('manage/quiz/detail/<pk>', views.detail_course_quiz, name='detail_quiz'),
    path('manage/quiz/create/', views.QuizCreateUpdateview.as_view(), name='create_quiz'),
    path('manage/quiz/update/<id>/', views.QuizCreateUpdateview.as_view(), name='update_quiz'),
    path('manage/quiz/delete/<id>/', views.QuizCreateUpdateview.as_view(), name='delete_quiz'),

    path('manage/quiz/<quiz_id>/questions/', views.AddQuestionsView.as_view(), name='add_questions'),
    # path('manage/quiz/<quiz_id>/questions/form/', views.question_form, name='question_form'),

    # path('manage/<quiz_id>/quiz/<pk>/answer/form/', views.answer_form, name='answer_form'),
    # path('manage/answer/form/<quiz_id>', views.answer_form, name='answer_form'),
    # path('manage/<quiz_id>/question/<pk>/answer/', views.answer, name='create_answer'),

    # path('manage/<quiz_id>/question/<pk>/answer/update/', views.AnswerUpdateView.as_view(), name='update_answer'),

    path('manage/quiz/active/<int:pk>', views.quiz_active, name='quiz_active'),

    path('create/question/<quiz_id>', views.question_form, name='create_question'),

    path('update/question/<question_id>', views.update_question, name='update_question'),
    path('delete/question/<question_id>', views.delete_question, name='delete_question'),

    # students
    path('', views.StudentQuizListView.as_view(), name='student_quiz_list'),
    path('<pk>/', views.quiz_view, name='quiz_detail'),
    path('<pk>/save/', views.save_quiz_view, name='save_view'),
    path('<pk>/data/', views.quiz_data_view, name='quiz_data_view'),
]

courses/forms.py
import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import inlineformset_factory
from django.utils.translation import gettext_lazy as _

from courses.models import Course, Module, GroupCourse


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('subject', 'title', 'overview', 'img','price')
        widgets = {
            'img': forms.FileInput(attrs={'class': 'form-control'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        img = cleaned_data.get('img')
        mb = img.size
        print(mb)
        if mb > 5096000:
            print('warning')
            self.add_error('img', _('Rasm hajmi 5MB dan katta'))


class ModulForm(forms.ModelForm):
    class Meta:
        model = Module
        fields = (
            'title',
            'description',

        )


ModuleFormSet = inlineformset_factory(Course, Module,
                                      fields=['title', 'description'],
                                      min_num=2,
                                      extra=1,
                                      can_delete=True,
                                      )


class GroupForm(forms.ModelForm):
    class Meta:
        model = GroupCourse
        fields = (
            'title', 'time_start', 'time_end',
        )
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'time_start': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
            'time_end': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'})
        }


class GroupSchedule(forms.Form):
    week_days = (
        ('1', 'dushanba'),
        ('2', 'seshanba'),
        ('3', 'chorshanba'),
        ('4', 'payshanba'),
        ('5', 'juma'),
        ('6', 'shanba'),
        ('0', 'yakshanba'),
    )

    days_out_off = [(datetime.date.today() + datetime.timedelta(i), datetime.date.today() + datetime.timedelta(i)) for i
                    in range(730)]

    days = forms.MultipleChoiceField(label='istisno kunlar(agar bo\'lsa)',
                                     help_text='2 va undan ortiq tanlash uchun ctrl + ni bosib tanlang',
                                     widget=forms.SelectMultiple(), choices=days_out_off, required=False)
    start_date = forms.DateField(label='Boshlash sanasi', widget=forms.DateInput(attrs={'type': 'date'}))
    days_of_the_week = forms.MultipleChoiceField(label='Hafta kunlari', widget=forms.CheckboxSelectMultiple(),
                                                 choices=week_days)

courses/index_view/views.py
from django.db.models import Count, Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView
from django.views.generic.base import TemplateResponseMixin, View

from account.forms import CourseEnrollForm
from account.models import Students
from courses.models import Subject, Course


class HomePage(TemplateResponseMixin, View):

    def get(self, request):
        return render(request, 'course/pages/index.html')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


home_page = HomePage.as_view()


class CourseListView(TemplateResponseMixin, View):
    template_name = 'course/pages/courses.html'

    def get(self, request, subject=None):
        subjects = Subject.objects.annotate(total_courses=Count(
            'courses', filter=Q(courses__active=True)))
        courses = Course.objects.filter(active=True).annotate(
            total_modules=Count('modules')
        )

        if request.GET.get('search_courses'):
            query = request.GET.get('search_courses')
            courses = courses.filter(
                Q(title__icontains=query) | Q(subject__title__icontains=query), active=True)

        if subject:
            subject = get_object_or_404(Subject, slug=subject)
            courses = courses.filter(subject=subject, active=True)

        return self.render_to_response({
            'subjects': subjects,
            'subject': subject,
            'courses': courses
        })


course_list_view = CourseListView.as_view()


class CourseDetailView(DetailView):
    model = Course
    template_name = 'course/pages/detail-course.html'
    r_user = None
    group = None

    def dispatch(self, request, *args, **kwargs):
        try:
            self.r_user = Students.objects.get(user=self.request.user)
            try:
                self.group = self.r_user.groupcourse.get(course__slug=self.kwargs['slug'])
            except:
                self.group = None
        except:
            self.r_user = None

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['r_user'] = self.r_user
        context['group'] = self.group
        context['enroll'] = CourseEnrollForm(self.object, self.r_user,
                                             initial={
                                                 'course': self.object,
                                             }
                                             )

        # form = CourseEnrollForm(self.request.POST, self.request.FILES)
        return context

courses/templates/dashboard/includes/header.html
{% load static %}
<header>
    <h2>
        <label for="nav-toggle">
            <span class="fas fa-bars"></span>
        </label>
        <span>{{ request.user.get_full_name }}</span>
        {#        {% now 'F : d : Y' %}#}

    </h2>

    <div class="user-wrapper">
        {#        <div class="notice">#}
        {#            <a href=""><span class="fas fa-sms position-relative"></span></a>#}
        {#            <span class="position-absolute top-1 translate-middle badge rounded-pill bg-warning badge-notice">4</span>#}
        {#        </div>#}
        {#        <div class="notice">#}
        {#            <a href=""><span class="fas fa-bell position-relative"></span></a>#}
        {#            <span class="position-absolute top-1 translate-middle badge rounded-pill bg-warning badge-notice">4</span>#}
        {#        </div>#}
        {% if request.user.profile_image %}
            <img src="{{ request.user.profile_image.url }}" alt="user_img" width="40" height="40">
        {% else %}
            <img src="{% static 'courses/images/man.png' %}" alt="user_img" width="40" height="40">

        {% endif %}
        <span class='fas '></span>
    </div>
</header>

courses/templates/dashboard/includes/sidebar.html
{% load static %}
{% url 'course:manage:dashboard' as dashboard %}
{% url 'course:manage:manage_course_list' as courses %}
{% url 'manage_group_list' as groups %}
{% url 'quiz:quiz_list' as quiz_list %}
{% url 'teacher_edit' request.user.pk as teacher_edit %}
{#{% url '' as Students %}#}
{#{% url '' as add_quiz %}#}
{#{% url '' as notice %}#}
<div class="sidebar">
    <a href="{% url 'course:homepage' %}" style="text-decoration: none;">
        <div class="sidebar-brand" style="display:flex; align-items:center;">
            <img width='70' src="{% static 'courses/images/logo-stable.png' %}" alt="">
            <div class="text__stable" style='display:flex;flex-direction:column; margin-left:10px;'>
                <span>Stable</span>
                <span>Education</span>
            </div>
            {% comment %} <h2><span class="fab fa-accusoft"></span><span>Stable Education </span></h2> {% endcomment %}
        </div>
    </a>
    <div class="sidebar-menu">
        <ul>
            <li><a class="{% if request.path == dashboard %} active{% endif %}"
                   href="{{ dashboard }}"><span
                    class="fas fa-igloo"></span><span>Boshqaruv paneli</span></a></li>
            <li><a class="{% if request.path == courses %} active {% endif %}"
                   href="{% url 'course:manage:manage_course_list' %}"><span
                    class=" fas fa-clipboard-list"></span><span>Kusrlar</span></a>
            <li><a class="{% if request.path == groups %} active {% endif %} "
                   href="{% url 'course:manage:manage_group_list' %}"><span
                    class="fas fa-users"></span><span>Guruhlar</span></a></li>
            </li>
            {#            <li><a href=""><span class="fas fa-shipping-fast"></span><span>Students</span></a>#}
            </li>
            <li><a class="{% if request.path == quiz_list %} active{% endif %}" href="{{ quiz_list }}"><span
                    class="fas fa-receipt"></span><span>Test Bo'limi</span></a></li>
            {#            <li><a href=""><span class="fas fa-clipboard-list"></span><span>E`lonlar</span></a></li>#}
        </ul>
    </div>
    <div class="stdudent-settings position-absolute bottom-0 h5">
        <ul>
            <li class="p-2"><a class="text-decoration-none p-3" style="color: white;"
                               href="{% url 'account:teacher_edit' %}"><span
                    class="fas fa-wrench"></span><span class="m-2">Profilni tahrirlash</span></a></li>
            <li class="p-2"><a class="text-decoration-none p-3" style="color: white;"
                               href="{% url 'account:log_out' %}"><span
                    class="fas fa-arrow-circle-left"></span><span class="m-2">Chiqish</span></a></li>
        </ul>
    </div>
</div>