edulive/urls.py
import random
import time
from django.views.static import serve

from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from account.models import CustomUser, Students
from get_sms import Getsms
from faker import Faker
from account.forms import RegisterUserForm
from django.http import HttpResponse
from get_sms import Getsms
from django.http import HttpResponse
#
# def create_user(request):
#     students = CustomUser.objects.all()[:100]

# for x in students:
#     Students.objects.create(user=x)
# fake = Faker()
# for x in range(1000):
#
#     name = fake.name()
#     if len(name.split(' '))==2:
#         username = str(name).split(' ')[0].lower()
#         phone_number = "99899000{:04d}".format(x)
#
#         data = {
#             'username': username,
#             'phone_number': phone_number,
#             'full_name': f"{name} {username.capitalize()}",
#             'email': fake.email(),
#             'password1': 'admin111',
#             'password2': 'admin111',
#         }
#         form = RegisterUserForm(data)
#         print(form.is_valid())
#         if form.is_valid():
#             print('valid')
#             form.save()
#             print('save')

# return redirect('course:homepage')
def send_s(request):
    login = 'Stable'
    password = '51v4N0y4R3N5rbcy122c'
    message = Getsms(login=login, password=password)
    phone = ['998997047646']
    result = message.send_message(phone_numbers=phone, text=f"sizning verifikatsiya kodingiz {123456}")
    return HttpResponse(result)
urlpatterns = [
    path('mvzona/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('news/', include('news.urls')),
    path('quiz/', include('quiz.urls')),
    path('create/', send_s),
    path('', include('courses.urls')),

    #path('__debug__/', include('debug_toolbar.urls')),
   #path('create/', sms_send, name='create')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),]

if settings.DEBUG:
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)

#urlpatterns += static(settings.MEDIA_URL,
#                      document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL,
#                      document_root=settings.STATIC_ROOT)
#

news/urls.py
from django.urls import path
from news.views import blog_news, blog_single_news, blog_search, offerta

app_name = 'news'

urlpatterns = [
    path('', blog_news, name='news'),
    path('<int:pk>/', blog_single_news, name='single_news'),
    path('search/', blog_search, name='search_news'),
    path('offerta/', offerta, name='offerta'),
]

quiz/urls.py
from django.urls import path
from quiz import views

app_name = 'quiz'

urlpatterns = [
    path('manage/quiz/list/', views.QuizListView.as_view(), name='quiz_list'),
    path('manage/quiz/detail/<pk>', views.detail_course_quiz, name='detail_quiz'),
    path('manage/quiz/create/', views.QuizCreateUpdateview.as_view(), name='create_quiz'),
    path('manage/quiz/update/<id>/', views.QuizCreateUpdateview.as_view(), name='update_quiz'),
    path('manage/quiz/delete/<id>/', views.QuizCreateUpdateview.as_view(), name='delete_quiz'),

    path('manage/quiz/<quiz_id>/questions/', views.AddQuestionsView.as_view(), name='add_questions'),
    # path('manage/quiz/<quiz_id>/questions/form/', views.question_form, name='question_form'),

    # path('manage/<quiz_id>/quiz/<pk>/answer/form/', views.answer_form, name='answer_form'),
    # path('manage/answer/form/<quiz_id>', views.answer_form, name='answer_form'),
    # path('manage/<quiz_id>/question/<pk>/answer/', views.answer, name='create_answer'),

    # path('manage/<quiz_id>/question/<pk>/answer/update/', views.AnswerUpdateView.as_view(), name='update_answer'),

    path('manage/quiz/active/<int:pk>', views.quiz_active, name='quiz_active'),

    path('create/question/<quiz_id>', views.question_form, name='create_question'),

    path('update/question/<question_id>', views.update_question, name='update_question'),
    path('delete/question/<question_id>', views.delete_question, name='delete_question'),

    # students
    path('', views.StudentQuizListView.as_view(), name='student_quiz_list'),
    path('<pk>/', views.quiz_view, name='quiz_detail'),
    path('<pk>/save/', views.save_quiz_view, name='save_view'),
    path('<pk>/data/', views.quiz_data_view, name='quiz_data_view'),
]

quiz/views.py
import os
from datetime import datetime

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.views.generic.base import TemplateResponseMixin, View

from account.models import Students
from courses.models import Course, GroupCourse
from quiz.forms import QuizForm, QuestionForm, answer_formset
from quiz.models import Quiz, Question, Result, Answer, Sertificate


class QuizListView(ListView):
    template_name = 'dashboard/quiz/quiz.html'
    context_object_name = 'quiz_list'
    model = Quiz

    def dispatch(self, request, *args, **kwargs):
        try:
            groups = request.user.groups.values_list('name', flat=True)[0]
        except:
            groups = None

        if groups == 'instructor':
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('course:homepage')

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(course__owner=self.request.user)


class QuizCreateUpdateview(TemplateResponseMixin, View):
    template_name = 'dashboard/quiz/quiz_form.html'
    obj = None
    course = None
    http_method_names = ['get', 'post', 'delete']

    def dispatch(self, request, id=None, *args, **kwargs):

        try:
            groups = request.user.groups.values_list('name', flat=True)[0]
        except:
            groups = None

        if groups == 'instructor':
            self.course = Course.objects.filter(owner=request.user)
            if id:
                self.obj = get_object_or_404(Quiz, pk=id, course__owner=request.user)
            if request.method.lower() == 'delete':
                return self.delete(request, id)

            return super(QuizCreateUpdateview, self).dispatch(request, id, *args, **kwargs)
        else:
            return redirect('course:homepage')

    def get(self, request, id=None):
        form = QuizForm(instance=self.obj)
        form.fields['course'].queryset = self.course
        return self.render_to_response({'form': form, 'object': self.obj})

    def post(self, request, id=None):
        form = QuizForm(request.POST, instance=self.obj)
        print(self.obj)
        form.fields['course'].queryset = self.course
        if form.is_valid():
            self.obj = form.save()
            return redirect('quiz:detail_quiz', pk=self.obj.pk)
        return self.render_to_response({'form': form})

    def delete(self, request, id):
        self.obj.delete()
        return HttpResponse('')


def quiz_active(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)

    if request.method == 'POST':
        active = request.POST.get('active')
        print(active)
        if active:
            quiz.active = True
            quiz.save()
            return HttpResponse('checked')
        else:
            quiz.active = False
            quiz.save()
            return HttpResponse(None)

    return HttpResponse('<input type="checkbox" hx-post="." hx-target="this" hx-trigger="click" value="check">')


def detail_course_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk, course__owner=request.user)
    context = {'object': quiz}
    return render(request, 'dashboard/quiz/course_quiz_detail.html', context)


def quiz_form(request, id=None):
    try:
        obj = Quiz.objects.get(pk=id, course__owner=request.user)
    except:
        obj = None
    form = QuizForm(instance=obj)
    form.fields['course'].queryset = Course.objects.filter(owner=request.user)
    contex = {'form': form}
    return render(request, 'dashboard/quiz/quiz_form.html', context=contex)


class AddQuestionsView(TemplateResponseMixin, View):
    template_name = 'dashboard/quiz/question_list.html'

    def get(self, request, quiz_id):
        quiz = get_object_or_404(Quiz, pk=quiz_id, course__owner=request.user)

        return self.render_to_response({
            'questions': quiz.questions.all(),
            'quiz': quiz,
        })

    def post(self, request, quiz_id):
        form = QuestionForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            obj = form.save()
            return render(request, 'dashboard/quiz/questions_detail.html', {'object': obj, 'quiz_id': quiz_id})


def question_detail(request, pk):
    question = get_object_or_404(Question, pk=pk, quiz__course__owner=request.user)
    context = {
        'object': question
    }
    return render(request, 'dashboard/quiz/questions_detail.html', context)


def question_form(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id, course__owner=request.user)
    print(quiz)
    form = QuestionForm(initial={'quiz': quiz})
    formset = answer_formset()

    if request.method == 'POST':

        form = QuestionForm(request.POST)
        formset = answer_formset(request.POST or None)
        print(form)
        if all([form.is_valid(), formset.is_valid()]):
            print('form is valid')
            question = form.save(commit=False)
            quiz_obj = type(form.cleaned_data['quiz'])
            print(quiz_obj)
            question.save()
            answers = formset.save(commit=False)
            print(question)
            for answer in answers:
                answer.question = question
                answer.save()
            print('post save boldi')
            return render(request, 'dashboard/manage/detail_question.html', {'question': question})

    return render(request, 'dashboard/manage/question_form.html',
                  {'formset': formset, 'form': form, 'quiz_id': quiz_id})


def update_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id, quiz__course__owner=request.user)

    formset = answer_formset(instance=question)
    form = QuestionForm(instance=question)
    print(formset)

    if request.method.lower() == 'post':
        form = QuestionForm(request.POST, instance=question)
        formset = answer_formset(request.POST, instance=question)
        print(formset)
        print('form=', form.is_valid(), 'formset=', formset.is_valid())
        print(formset.errors)
        if all([form.is_valid(), formset.is_valid()]):
            question = form.save(commit=False)
            question.save()
            answers = formset.save(commit=False)
            for answer in answers:
                answer.question = question
                answer.save()
            # return HttpResponse('')
            return render(request, 'dashboard/manage/detail_question.html', {'question': question})
    context = {
        'formset': formset,
        'form': form,
        'quiz_id': question.quiz.id,
        'question_id': question_id
    }

    return render(request, 'dashboard/manage/question_update_form.html', context)


def delete_question(request, question_id):
    try:
        groups = request.user.groups.values_list('name', flat=True)[0]
    except:
        groups = None
    if groups == 'instructor':
        question = get_object_or_404(Question, pk=question_id, quiz__course__owner=request.user)
        question.delete()
        return HttpResponse('')


# student quiz views
class StudentQuizListView(ListView):
    model = Quiz
    template_name = 'students/quiz/quiz_list.html'
    quiz = None

    def get_queryset(self):
        quiz_list = []
        try:
            group = GroupCourse.objects.filter(end_date__gte=datetime.now())
            if group:
                for g in group:
                    quiz = g.course.quizs.all().first()
                    print(g.course.quizs.all())
                    if quiz is not None:
                        quiz_list.append(quiz)
        except:
            pass

        print(quiz_list)
        return quiz_list


def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    try:
        r = Result.objects.get(quiz=quiz, student__user=request.user)
        if r.score >= quiz.score_to_pass:
            return redirect('quiz:student_quiz_list')
    except:
        pass

    return render(request, 'students/quiz/quiz_detail.html', context={'object': quiz})
    # try:
    #     result = Result.objects.get(student__user=request.user, quiz=quiz)
    # except:
    #     result = None
    # if not result:
    #     quiz = Quiz.objects.get(pk=pk)
    #     return render(request, 'students/dashboard/quiz/quiz_detail.html', context={'object': quiz})
    # else:
    #     return redirect('student_quiz_list')


def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    # try:
    #     result = Result.objects.get(student__user=request.user, quiz=quiz)
    # except:
    #     result = None
    # if not result:
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    # result = quiz.result.filter(student=request.user)
    # if result:
    #     print('bu user test yechgan')
    # else:
    #     print('user test hali yechmagan')
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })


def save_quiz_view(request, pk):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        questions = []
        data = request.POST
        data_ = dict(data.lists())
        print(data_)
        data_.pop('csrfmiddlewaretoken')
        print(data_)

        for k in data_.keys():
            question = Question.objects.get(text=k)
            questions.append(question)
        print('----------------', len(questions), '----------------')
        user = Students.objects.get(user=request.user)
        print(user)
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        # multipler = 100 / quiz.number_of_questions
        multipler = 100 / len(questions)
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(str(q))

quiz/templates/dashboard/quiz/course_quiz_detail.html
<div hx-target="this" hx-swap="outerHTML" class="row border p-3 shadow-sm mx-3 my-3">
    <div class="col-md-6">
        <a href="{% url 'quiz:add_questions' object.id %}"><h2>{{ object.title }}</h2></a>
        <p>{{ object.course }}</p>
        <div class="row gap-2">
            <button hx-get="{% url 'quiz:update_quiz' object.id %}" class="col-md-4 btn btn-outline-warning">update
            </button>
            <button hx-delete="{% url 'quiz:delete_quiz' object.id %}" hx-confirm="{{ object }} o'chirish"
                    class="col-md-4 btn btn-outline-danger">delete
            </button>
            <form class="col-md-4">
                {% csrf_token %}
                <div class="form-check form-switch" style="font-size: 1.5rem;">
                    <input name="active"
                           hx-post="{% url 'quiz:quiz_active' object.pk %}"
                           hx-target="this" hx-trigger="click" hx-swap="innerHTML"
                           class="form-check-input" type="checkbox"
                           {% if object.active == True %}checked{% endif %}
                           role="switch"
                           id="{{ object.pk }}">
                    <label class="form-check-label"
                           for="{{ object.pk }}">on/off</label>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-6">
        <p>time: {{ object.time }}</p>
        <p>o'tish bali: {{ object.score_to_pass }}%</p>
        <p>savollar: {{ object.number_of_questions }}ta lik</p>
        <p>umumiy savollar soni: {{ object.questions.count }}</p>
    </div>
</div>

quiz/templates/dashboard/quiz/question_form.html
{% load crispy_forms_tags %}
<div hx-target="this" class="m-3 p-2">
    <form action="" class="">
        {% csrf_token %}
        <div class="row mt-3">
            <fieldset>
                <legend>Test Savoli</legend>
                {{ form|crispy }}
            </fieldset>
        </div>
        <button hx-post="." class="btn btn-outline-dark mt-3">saqlash</button>
    </form>
</div>

quiz/templates/dashboard/quiz/question_list.html
{% extends "dashboard/layout/base.html" %}
{% load crispy_forms_tags %}
{% load course %}
{% load static %}


{% block title %}
    quiz
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'quiz/css/quiz_style.css' %}">
{% endblock style %}
{% block content %}
    <main>
        {#        <h2 class="mb-3 text-center">{{ quiz_id.course }}</h2>#}
        <div class="block__btn">
            <button hx-target="#wrapper-form" hx-get="{% url 'quiz:create_question' quiz.pk %}" hx-swap="innerHTML"
                    class="btn btn-warning">savol qo'shish
            </button>
        </div>
        <div class="wrapper-quiz">

            <div class="wrapper-questions">


                <div class="block__questions">

                    <ul class="list__questions" id="list_question">

                        {% for question in questions %}
                            {% include 'dashboard/manage/detail_question.html' %}
                        {% endfor %}

                    </ul>

                </div>

            </div>

            <div class="wrapper-form" id="wrapper-form">


            </div>
        </div>
    </main>
{% endblock content %}

quiz/templates/dashboard/quiz/questions_detail.html
<div hx-target="this" hx-swap="outerHTML" class="row h-4 border p-3 shadow-sm mx-3 my-3">
    <div class="col-md-6">
        <h2>{{ object.text }}</h2>

    </div>
    <div class="col-md-6">
        <div class="d-flex justify-content-end gap-2">
            <button class="btn btn-outline-warning">update</button>
            <button hx-post="{% url 'quiz:question_delete' object.pk %}" hx-confirm="{{ object }}ni o'chirish"
                    class="btn btn-outline-danger">delete
            </button>
        </div>
    </div>
    <hr>

    <div class="d-flex justify-content-between">
        <h3>Javoblar</h3>
        <div class="d-flex">
            <button hx-get="{% url 'quiz:answer_form' quiz_id object.id %}" hx-swap="afterend" class="btn">javob
                qo'shish
            </button>
        </div>
    </div>
</div>

quiz/templates/dashboard/quiz/quiz.html
{% extends "dashboard/layout/base.html" %}
{% load crispy_forms_tags %}
{% load course %}
{% load static %}
{% block title %}

{% endblock %}
{% block content %}
    <main>
        <div class="resent-grid" style="grid-template-columns: 100%">
            <div class="projects">

                <div class="card">
                    <div class="card-header ">
                        <h3>Quiz form</h3>
                        <button hx-get="{% url 'quiz:create_quiz' %}" hx-target="#quizform">Test Yaratish<span
                                class="fas fa-arrow-right"></span></button>

                    </div>

                    <div class="card-body">
                        <div id="quizform"></div>

                        {% for object in quiz_list %}
                            {% include 'dashboard/quiz/course_quiz_detail.html' %}
                        {% endfor %}


                    </div>

                </div>
            </div>


            {#            <div class="card">#}
            {#                <div class="card-header">#}
            {#                    <h3>O'quvchilar ro'yxati</h3>#}
            {##}
            {#                    <button>See all <span class="fas fa-arrow-right"></span></button>#}
            {#                </div>#}
            {#                <div class="card-body">#}
            {#                    card#}
            {#                </div>#}
            {#            </div>#}
        </div>
    </main>
{% endblock content %}

quiz/templates/dashboard/quiz/quiz_form.html
{% load crispy_forms_tags %}
{% load static %}
<div hx-target="this" hx-swap="outerHTML" class="row m-3">
    <form action="">
        {% csrf_token %}

        {{ form.media }}
        {{ form.course|as_crispy_field }}
        {{ form.title|as_crispy_field }}
        {{ form.description|as_crispy_field }}
        {{ form.number_of_questions|as_crispy_field }}
        {{ form.score_to_pass|as_crispy_field }}
        {{ form.time|as_crispy_field }}
        {{ form.difficulty|as_crispy_field }}
        {#        {{ form.active|as_crispy_field }}#}

        {% if object %}
            <button hx-post="{% url 'quiz:update_quiz' object.id %}" class="btn btn-outline-dark mt-3 align-items-end">
                saqlash
            </button>

            <button hx-post="{% url 'quiz:detail_quiz' object.id %}" class="btn btn-outline-dark mt-3 align-items-end">
                orqaga qaytish
            </button>
        {% else %}
            <button hx-post="{% url 'quiz:create_quiz' %}" class="btn btn-outline-dark mt-3 align-items-end">submit
            </button>

        {% endif %}
    </form>
</div>