account/urls.py
from django.urls import path, include
from .account_views import views
from .students import views as s_views
from django.contrib.auth.views import LoginView, LogoutView
from account.utils.payme import PaymeView

app_name = 'account'

urlpatterns = [
    path('login/', views.login_view, name='log_in'),
    path('logout/', views.log_out, name='log_out'),
    path('signup/', views.register, name='sign_up'),
    path('verify/', views.verify, name='verify'),
    path('resend/', views.otp, name='resend'),

    path('teacher/edit/', views.user_update_view, name='teacher_edit'),

    # change
    path(
        "password_change/", views.PasswordChangeView.as_view(), name="password_change"
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset/", views.PasswordResetView.as_view(template_name='account/change/reset_password.html',
                                                            email_template_name='new/reset_password_email.html'),
         name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(template_name='account/change/reset_password_done.html'),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(template_name='account/change/reset_password_confirm.html'),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(template_name='account/change/reset_done.html'),
        name="password_reset_complete",
    ),

    path('enroll-course/', s_views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/', s_views.StudentCourseListView.as_view(), name='student_course_list'),
    # path('course/<slug:group_s>/<slug:course_s>/', s_views.StudentCourseDetailView.as_view(),
    #      name='student_course_detail'),
    path('course/<slug:group_s>/<slug:course_s>/', s_views.student_course_module_list, name='student_course_detail'),
    path('course/<pk>/<module_id>/', s_views.StudentCourseDetailView.as_view(), name='student_course_detail_module'),
    # path('profile/', views.dashboard_student, name='stdudent_dashboard'),

    path('profile/', s_views.StudentdDashboardView.as_view(), name='stdudent_dashboard'),
    path('profile/edit/', s_views.student_update_view, name='user_edit_profile'),
    path('payment_info/', s_views.StudentPaymentInfo.as_view(), name='payment_info'),

    # path('module/<slug:course_slug>/<int:pk>/', s_views.ModuleContentDetail.as_view(), name='module_detail'),
    path('module/<slug:course_slug>/<int:pk>/', s_views.ModuleDetailView.as_view(), name='module_detail'),

    # path('quiz/', include('students.quiz.urls')),
    path('sertificate/<uuid>/', s_views.ViewPDF.as_view(), name='sertificate'),
    path('payment', PaymeView.as_view(), name='payment'),
]

edulive/urls.py
import random
import time
from django.views.static import serve

from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from account.models import CustomUser, Students
from get_sms import Getsms
from faker import Faker
from account.forms import RegisterUserForm
from django.http import HttpResponse
from get_sms import Getsms
from django.http import HttpResponse
#
# def create_user(request):
#     students = CustomUser.objects.all()[:100]

# for x in students:
#     Students.objects.create(user=x)
# fake = Faker()
# for x in range(1000):
#
#     name = fake.name()
#     if len(name.split(' '))==2:
#         username = str(name).split(' ')[0].lower()
#         phone_number = "99899000{:04d}".format(x)
#
#         data = {
#             'username': username,
#             'phone_number': phone_number,
#             'full_name': f"{name} {username.capitalize()}",
#             'email': fake.email(),
#             'password1': 'admin111',
#             'password2': 'admin111',
#         }
#         form = RegisterUserForm(data)
#         print(form.is_valid())
#         if form.is_valid():
#             print('valid')
#             form.save()
#             print('save')

# return redirect('course:homepage')
def send_s(request):
    login = 'Stable'
    password = '51v4N0y4R3N5rbcy122c'
    message = Getsms(login=login, password=password)
    phone = ['998997047646']
    result = message.send_message(phone_numbers=phone, text=f"sizning verifikatsiya kodingiz {123456}")
    return HttpResponse(result)
urlpatterns = [
    path('mvzona/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('news/', include('news.urls')),
    path('quiz/', include('quiz.urls')),
    path('create/', send_s),
    path('', include('courses.urls')),

    #path('__debug__/', include('debug_toolbar.urls')),
   #path('create/', sms_send, name='create')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),]

if settings.DEBUG:
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)

#urlpatterns += static(settings.MEDIA_URL,
#                      document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL,
#                      document_root=settings.STATIC_ROOT)
#

news/urls.py
from django.urls import path
from news.views import blog_news, blog_single_news, blog_search, offerta

app_name = 'news'

urlpatterns = [
    path('', blog_news, name='news'),
    path('<int:pk>/', blog_single_news, name='single_news'),
    path('search/', blog_search, name='search_news'),
    path('offerta/', offerta, name='offerta'),
]

account/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser, User
from django.db import models

from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(
                "Superuser must have is_staff=True."
            )
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(
                "Superuser must have is_superuser=True."
            )

        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    username = models.CharField(max_length=100, blank=True, null=True)

    email = models.EmailField(unique=True)
    phone_number = models.CharField(_('phone_number'), unique=True, max_length=20)
    date_of_birth = models.DateField(blank=True, null=True)
    profile_image = models.ImageField(upload_to='user/images/', blank=True)

    # father name
    father_name = models.CharField(_('father_name'), max_length=100, blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['phone_number']

    objects = CustomUserManager()

    def get_full_name(self):
        return f"{self.last_name} {self.first_name}  {self.father_name}"
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Students(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.PROTECT, related_name='students',
                                related_query_name='students')
    pasport = models.FileField('pasport', upload_to='students/pasport/', blank=True)
    selfi_pasport = models.FileField('selfipasport', upload_to='students/pasport/', blank=True)
    date_of_birth = models.DateField(blank=True, null=True)

    def get_full_name(self):
        return f"{self.user.last_name} {self.user.first_name}"

    def __str__(self):
        return f"{self.user}"


class Teachers(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.PROTECT)
    bio = models.TextField(blank=True)

    # skills = models.ManyToManyField('Skills', blank=True)
    # socials = models.ManyToManyField('Socials', blank=True, verbose_name='ijtimoiy tarmoqlar')
    grade = models.CharField(max_length=100, blank=True)

quiz/models.py
import os
import random
from io import BytesIO

import uuid as uuid
from django.db import models
import qrcode
from io import BytesIO
from django.core.files import File as F
from PIL import ImageDraw, Image as Img
from django.urls import reverse

from account.models import Students
from courses.fields import OrderField
from courses.models import Course


# Create your models here.
class Quiz(models.Model):
    DIFF_CHOICES = (
        ('easy', 'easy'),
        ('medium', 'medium'),
        ('hard', 'hard'),
    )

    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='quizs')
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    number_of_questions = models.IntegerField()
    score_to_pass = models.IntegerField(help_text="O'tish uchun eng past ball")
    time = models.IntegerField(help_text="test yechish uchun vaqt davomiyligi")
    created = models.DateTimeField(auto_now_add=True)
    difficulty = models.CharField(max_length=255, choices=DIFF_CHOICES)
    active = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.course}: {self.title}"

    def get_questions(self):
        questions = list(self.questions.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    order = OrderField(blank=True, for_fields=['quiz'], null=True)

    # def __str__(self):
    #     return f"{self.text}"

    def get_answers(self):
        answers = list(self.answers.all())
        random.shuffle(answers)
        return answers

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['created']


class Answer(models.Model):
    text = models.TextField(blank=True, null=True)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    created = models.DateTimeField(auto_now_add=True)
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    order = OrderField(blank=True, for_fields=['question'], null=True)

    def __str__(self):
        return f'savol: {self.question.text} - javob: {self.correct}'

    class Meta:
        ordering = ['-created']


class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='result', related_query_name='result')
    student = models.ForeignKey(Students, on_delete=models.CASCADE, related_name='result')
    score = models.FloatField()
    attempts = models.IntegerField(verbose_name='urinishlar soni', help_text='Urinishlar soni', default=1)

    def __str__(self):
        return f"{self.student}: result {self.score}"

    def result(self):
        return f"{self.student}: result {self.score}"


class Sertificate(models.Model):
    def content_image_name(instance, filename):
        return '/'.join([f'{instance.course}', str(instance.student), filename])

    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='sertificate')
    student = models.ForeignKey(Students, on_delete=models.CASCADE, related_name='sertificate',
                                related_query_name='sertificate')
    qr_photo = models.ImageField(editable=False, upload_to=content_image_name, blank=True)
    created = models.DateField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('account:sertificate', kwargs={'uuid': self.uuid})

    def save(self, *args, **kwargs):
        try:
            if len(self.qr_photo) > 0:
                os.remove(self.qr_photo.path)
        except:
            pass

        qrcode_img = qrcode.make(f"{self.get_absolute_url()}")
        canvas = Img.new('RGB', (450, 450), 'white')
        draw = ImageDraw.Draw(canvas)
        canvas.paste(qrcode_img)
        fname = f"{str(self.student).strip(' ')}" + '.png'
        buffer = BytesIO()
        canvas.save(buffer, 'PNG')
        self.qr_photo.save(fname, F(buffer), save=False)
        canvas.close()
        super().save(*args, **kwargs)

account/templates/students/layout/_sidebar_module.html
{% load static %}
{% url 'stdudent_dashboard' as dashboard %}
{% url 'student_course_list' as courses %}
{% url 'quiz_list' as add_quiz %}
{#{% url '' as Students %}#}
{#{% url '' as add_quiz %}#}
{#{% url '' as notice %}#}
<div class="sidebar"
     style="background-color: #2b2d42;overflow-y: scroll;display: flex;flex-direction: column;justify-content: space-between ">
    <div>
        <a href="{% url 'course:homepage' %}" style="text-decoration: none;">
            <div class="sidebar-brand" style="display:flex; align-items:center;">
                <img width='70' src="{% static 'courses/home/images/logo-stable.png' %}" alt="">
                <div class="text__stable" style='display:flex;flex-direction:column; margin-left:10px;'>
                    <span>Stable</span>
                    <span>Education</span>
                </div>
                {% comment %} <h2><span class="fab fa-accusoft"></span><span>Stable Education </span></h2> {% endcomment %}
            </div>

        </a>

        <div class="sidebar-menu">
            <ul>
                <li><a class="{% if request.path == dashboard %} active{% endif %}"
                       href="{% url 'account:stdudent_dashboard' %}"><span
                        class="fas fa-igloo"></span><span>Dashboard</span></a></li>
            </ul>
            <hr class="text-light">
            <ul>
                {% for module in modules %}

                    <li style="font-size:.9rem;">
                    <a style="font-size: .9rem;" class="{% if module == object %} active {% endif %}"
                       href="{% url 'account:module_detail' course.slug module.pk %}">{{ forloop.counter }})<span
                            style="font-size: .9rem;">{{ module.title|truncatechars:30 }}</span></a>
                {% endfor %}

            </ul>

        </div>
    </div>


    <div class="stdudent-settings  h5">
        <ul>
            <li class="p-2"><a class="text-decoration-none p-3" style="color: white;"
                               href="{% url 'account:user_edit_profile' %}"><span class="fas fa-wrench"></span><span
                    class="m-2">Profil tahrirlash</span></a></li>
            <li class="p-2"><a class="text-decoration-none p-3" style="color: white;"
                               href="{% url 'account:log_out' %}"><span class="fas fa-arrow-circle-left"></span><span
                    class="m-2">Chiqish</span></a></li>
        </ul>

    </div>

</div>

account/templates/students/layout/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- line awesome   -->
    <link rel="stylesheet"
          href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
    <!-- CSS bootstrapt -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <!-- CSS local    -->
    <link rel="stylesheet" href="{% static 'students/css/accordion.css' %}">
    <link rel="stylesheet" href="{% static 'students/css/calendar.css' %}">

    <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">

    <title>Document</title>
</head>


<body>
{% if request.user.is_authenticated %}

    <input type="checkbox" id="nav-toggle">
    {% block sidebar %}
        {% include 'students/includes/_sidebar.html' %}
    {% endblock %}


    <div class="main-content">

        {% include  'students/includes/_header.html' %}

        {% block content %}{% endblock %}
    </div>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{csrf_token}}';
        })
    </script>
{% endif %}

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://unpkg.com/htmx.org@1.7.0"></script>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
></script>
{#<script>#}
{#    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))#}
{#    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {#}
{#        return new bootstrap.Tooltip(tooltipTriggerEl)#}
{#    })#}
{#</script>#}

<script>
    $(document).ready(function () {

        {% block domready %}

        {% endblock %}
    });


</script>
{% block js %}

{% endblock %}
</html>