account/urls.py
from django.urls import path, include
from .account_views import views
from .students import views as s_views
from django.contrib.auth.views import LoginView, LogoutView
from account.utils.payme import PaymeView

app_name = 'account'

urlpatterns = [
    path('login/', views.login_view, name='log_in'),
    path('logout/', views.log_out, name='log_out'),
    path('signup/', views.register, name='sign_up'),
    path('verify/', views.verify, name='verify'),
    path('resend/', views.otp, name='resend'),

    path('teacher/edit/', views.user_update_view, name='teacher_edit'),

    # change
    path(
        "password_change/", views.PasswordChangeView.as_view(), name="password_change"
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset/", views.PasswordResetView.as_view(template_name='account/change/reset_password.html',
                                                            email_template_name='new/reset_password_email.html'),
         name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(template_name='account/change/reset_password_done.html'),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(template_name='account/change/reset_password_confirm.html'),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(template_name='account/change/reset_done.html'),
        name="password_reset_complete",
    ),

    path('enroll-course/', s_views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/', s_views.StudentCourseListView.as_view(), name='student_course_list'),
    # path('course/<slug:group_s>/<slug:course_s>/', s_views.StudentCourseDetailView.as_view(),
    #      name='student_course_detail'),
    path('course/<slug:group_s>/<slug:course_s>/', s_views.student_course_module_list, name='student_course_detail'),
    path('course/<pk>/<module_id>/', s_views.StudentCourseDetailView.as_view(), name='student_course_detail_module'),
    # path('profile/', views.dashboard_student, name='stdudent_dashboard'),

    path('profile/', s_views.StudentdDashboardView.as_view(), name='stdudent_dashboard'),
    path('profile/edit/', s_views.student_update_view, name='user_edit_profile'),
    path('payment_info/', s_views.StudentPaymentInfo.as_view(), name='payment_info'),

    # path('module/<slug:course_slug>/<int:pk>/', s_views.ModuleContentDetail.as_view(), name='module_detail'),
    path('module/<slug:course_slug>/<int:pk>/', s_views.ModuleDetailView.as_view(), name='module_detail'),

    # path('quiz/', include('students.quiz.urls')),
    path('sertificate/<uuid>/', s_views.ViewPDF.as_view(), name='sertificate'),
    path('payment', PaymeView.as_view(), name='payment'),
]

courses/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from courses.index_view import views as index

app_name = 'course'

urlpatterns = [
    path('', index.home_page, name='homepage'),
    path('course/', index.course_list_view, name='course_list'),

    path('subject/<slug:subject>/', index.CourseListView.as_view(),
         name='course_list_subject'),
    path('<slug:slug>/', index.CourseDetailView.as_view(), name='course_detail'),

    # dashboard urls
    path('course/manage/', include('courses.urls_manage')),
]

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL,
#                          document_root=settings.MEDIA_ROOT)

#urlpatterns += static(settings.STATIC_URL,
#                      document_root=settings.STATIC_ROOT)

edulive/urls.py
import random
import time
from django.views.static import serve

from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from account.models import CustomUser, Students
from get_sms import Getsms
from faker import Faker
from account.forms import RegisterUserForm
from django.http import HttpResponse
from get_sms import Getsms
from django.http import HttpResponse
#
# def create_user(request):
#     students = CustomUser.objects.all()[:100]

# for x in students:
#     Students.objects.create(user=x)
# fake = Faker()
# for x in range(1000):
#
#     name = fake.name()
#     if len(name.split(' '))==2:
#         username = str(name).split(' ')[0].lower()
#         phone_number = "99899000{:04d}".format(x)
#
#         data = {
#             'username': username,
#             'phone_number': phone_number,
#             'full_name': f"{name} {username.capitalize()}",
#             'email': fake.email(),
#             'password1': 'admin111',
#             'password2': 'admin111',
#         }
#         form = RegisterUserForm(data)
#         print(form.is_valid())
#         if form.is_valid():
#             print('valid')
#             form.save()
#             print('save')

# return redirect('course:homepage')
def send_s(request):
    login = 'Stable'
    password = '51v4N0y4R3N5rbcy122c'
    message = Getsms(login=login, password=password)
    phone = ['998997047646']
    result = message.send_message(phone_numbers=phone, text=f"sizning verifikatsiya kodingiz {123456}")
    return HttpResponse(result)
urlpatterns = [
    path('mvzona/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('news/', include('news.urls')),
    path('quiz/', include('quiz.urls')),
    path('create/', send_s),
    path('', include('courses.urls')),

    #path('__debug__/', include('debug_toolbar.urls')),
   #path('create/', sms_send, name='create')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),]

if settings.DEBUG:
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)

#urlpatterns += static(settings.MEDIA_URL,
#                      document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL,
#                      document_root=settings.STATIC_ROOT)
#

news/urls.py
from django.urls import path
from news.views import blog_news, blog_single_news, blog_search, offerta

app_name = 'news'

urlpatterns = [
    path('', blog_news, name='news'),
    path('<int:pk>/', blog_single_news, name='single_news'),
    path('search/', blog_search, name='search_news'),
    path('offerta/', offerta, name='offerta'),
]

courses/forms.py
import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import inlineformset_factory
from django.utils.translation import gettext_lazy as _

from courses.models import Course, Module, GroupCourse


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('subject', 'title', 'overview', 'img','price')
        widgets = {
            'img': forms.FileInput(attrs={'class': 'form-control'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        img = cleaned_data.get('img')
        mb = img.size
        print(mb)
        if mb > 5096000:
            print('warning')
            self.add_error('img', _('Rasm hajmi 5MB dan katta'))


class ModulForm(forms.ModelForm):
    class Meta:
        model = Module
        fields = (
            'title',
            'description',

        )


ModuleFormSet = inlineformset_factory(Course, Module,
                                      fields=['title', 'description'],
                                      min_num=2,
                                      extra=1,
                                      can_delete=True,
                                      )


class GroupForm(forms.ModelForm):
    class Meta:
        model = GroupCourse
        fields = (
            'title', 'time_start', 'time_end',
        )
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'time_start': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
            'time_end': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'})
        }


class GroupSchedule(forms.Form):
    week_days = (
        ('1', 'dushanba'),
        ('2', 'seshanba'),
        ('3', 'chorshanba'),
        ('4', 'payshanba'),
        ('5', 'juma'),
        ('6', 'shanba'),
        ('0', 'yakshanba'),
    )

    days_out_off = [(datetime.date.today() + datetime.timedelta(i), datetime.date.today() + datetime.timedelta(i)) for i
                    in range(730)]

    days = forms.MultipleChoiceField(label='istisno kunlar(agar bo\'lsa)',
                                     help_text='2 va undan ortiq tanlash uchun ctrl + ni bosib tanlang',
                                     widget=forms.SelectMultiple(), choices=days_out_off, required=False)
    start_date = forms.DateField(label='Boshlash sanasi', widget=forms.DateInput(attrs={'type': 'date'}))
    days_of_the_week = forms.MultipleChoiceField(label='Hafta kunlari', widget=forms.CheckboxSelectMultiple(),
                                                 choices=week_days)

courses/index_view/views.py
from django.db.models import Count, Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView
from django.views.generic.base import TemplateResponseMixin, View

from account.forms import CourseEnrollForm
from account.models import Students
from courses.models import Subject, Course


class HomePage(TemplateResponseMixin, View):

    def get(self, request):
        return render(request, 'course/pages/index.html')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


home_page = HomePage.as_view()


class CourseListView(TemplateResponseMixin, View):
    template_name = 'course/pages/courses.html'

    def get(self, request, subject=None):
        subjects = Subject.objects.annotate(total_courses=Count(
            'courses', filter=Q(courses__active=True)))
        courses = Course.objects.filter(active=True).annotate(
            total_modules=Count('modules')
        )

        if request.GET.get('search_courses'):
            query = request.GET.get('search_courses')
            courses = courses.filter(
                Q(title__icontains=query) | Q(subject__title__icontains=query), active=True)

        if subject:
            subject = get_object_or_404(Subject, slug=subject)
            courses = courses.filter(subject=subject, active=True)

        return self.render_to_response({
            'subjects': subjects,
            'subject': subject,
            'courses': courses
        })


course_list_view = CourseListView.as_view()


class CourseDetailView(DetailView):
    model = Course
    template_name = 'course/pages/detail-course.html'
    r_user = None
    group = None

    def dispatch(self, request, *args, **kwargs):
        try:
            self.r_user = Students.objects.get(user=self.request.user)
            try:
                self.group = self.r_user.groupcourse.get(course__slug=self.kwargs['slug'])
            except:
                self.group = None
        except:
            self.r_user = None

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['r_user'] = self.r_user
        context['group'] = self.group
        context['enroll'] = CourseEnrollForm(self.object, self.r_user,
                                             initial={
                                                 'course': self.object,
                                             }
                                             )

        # form = CourseEnrollForm(self.request.POST, self.request.FILES)
        return context

courses/templates/course/include/_footer.html
{% load static %}
<!-- ======= Footer ======= -->
<footer id="footer">

    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-md-6 footer-contact">
                    <h1 class="logo me-auto"><a href="{% url 'course:homepage' %}" class="logo"><img width='200'
                                                                                                     src="{% static 'courses/images/document.png' %}"
                                                                                                     alt=""></a></h1>
                    <p>
                        1706258501 - Buxoro viloyati, Shofirkon tumani, Shofirkon shahri<br><br>
                        <strong>Phone:</strong> +9989 99 700 99 44<br>
                        <strong>Email:</strong> stableeducation@gmail.com<br>
                    </p>
                </div>

                <div class="col-lg-2 col-md-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                    </ul>
                </div>
                <div class="col-lg-6 col-md-6 footer-newsletter">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d885.4322143951968!2d64.43926902924171!3d39.77175752948709!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f5005a6bbbc7b91%3A0x355d0d7aad095cab!2sSTABLE%20EDUCATION!5e1!3m2!1suz!2s!4v1650635867295!5m2!1suz!2s"
                            width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                            referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
                {% comment %} <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div> {% endcomment %}

                {% comment %} <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div> {% endcomment %}

            </div>
        </div>
    </div>

    <div class="container d-md-flex py-4">

        <div class="me-md-auto text-center text-md-start">
            <div class="copyright">
                &copy; Copyright by<strong><span>Stable Education</span></strong>. All Rights Reserved
            </div>
            <div class="credits">

            </div>
        </div>
        <div class="social-links text-center text-md-end pt-3 pt-md-0">
            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
    </div>
</footer><!-- End Footer -->

courses/templates/course/include/_header.html
{% load static %}
{% load account %}
{% url 'course:homepage' as home %}
{% url 'course:course_list' as course_list %}
{% url 'news:news' as news %}
{% comment %} {% profil request.user as std %} {% endcomment %}
<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center justify-content-speace-between">
    <div class="container d-flex justify-content-between align-items-center">

        <h1 class="logo me-auto"><a href="{% url 'course:homepage' %}" class="logo"><img
                src="{% static 'courses/images/document.png' %}" alt=""></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt=""></a>-->

        <nav id="navbar" class="navbar order-last order-lg-0">
            <ul>
                <li><a class="nav-link scrollto {% if request.path == home %}active {% endif %}"
                       href="{% url 'course:homepage' %}">Bosh sahifa</a></li>
                <li><a class="nav-link scrollto {% if request.path == course_list %}active {% endif %}"
                       href="{{ course_list }}">Kurslar</a></li>
                <li><a class="nav-link scrollto {% if request.path == news %}active {% endif %}"
                       href="{{ news }}">Yangiliklar</a></li>

                {#          <li><a class="nav-link scrollto" {% if not home%} href="{% url 'course:homepage' %}" {% else %} href="#about"{% endif %}  >About</a></li>#}

                <li><a class="nav-link scrollto" {% if request.path != home %}
                       href="{% url 'course:homepage' %}#services" {% else %}
                       href="#services"{% endif %}>Yo'nalishlar</a></li>
                <li><a class="nav-link scrollto" {% if request.path != home %}
                       href="{% url 'course:homepage' %}#team" {% else %} href="#team"{% endif %}>Team</a></li>
                <li><a class="nav-link scrollto" {% if request.path != home %}
                       href="{% url 'course:homepage' %}#contact" {% else %} href="#contact"{% endif %}>Contact</a></li>
            </ul>


            <i class="bi bi-list mobile-nav-toggle"></i>

            {% if request.user.is_authenticated %}
                <button data-account class="account btn bi bi-person-circle">
                </button>
                <small class="users-name">{{ request.user|capfirst }}</small>
            {% else %}
                <a href="{% url 'account:log_in' %}">
                    <button style='font-size:1.4rem;' class=" btn bi-box-arrow-right"><span style='font-weight:bold'> Kirish</span>
                    </button>
                </a>

            {% endif %}


            <!--account profile -->


            {% comment %} modalniy okno {% endcomment %}
            <!--account profile -->
            <div class="account-profile hidden" data-aos="zoom-in">
                <div id="close-form" data-close style='font-weight:900;' class="text-start bold bi bi-x-lg"></div>
                <div class="wrapper_user_info d-flex flex-column justify-content-center">

                    {% with std.user.last_name|length  as last %}
                        {% with len|add:-1 as first %}
                            {% if std.avatar %}
                                <img src="{{ std.avatar.url }}" alt="{{ std.avatar }}">
                                {#                    {{ std.avatar }}#}
                            {% elif  std.user.last_name|slice:first|last == 'a' %}
                                <img src="{% static 'courses/images/woman.png' %}" alt="">

                            {% else %}
                                <img src="{% static 'courses/images/man.png' %}" alt="">

                            {% endif %}
                        {% endwith %}
                    {% endwith %}


                    <h3>{{ request.user.get_full_name }}</h3>
                    {% if 'instructor' == request.user.groups.get.name %}
                        Teacher

                    {% elif std %}
                        Learner
                    {% endif %}
                    <hr>
                </div>
                <div class="account_profile_menu">
                    <ul>
                        {% if 'instructor' in request.user.groups.get.name %}

                            <li>
                                <a class="active" href="{% url 'course:manage:dashboard' %}"><i
                                        class="mx-3 h3 bi bi-speedometer"></i><span>dashboard</span>
                                </a>
                            </li>
                        {% endif %}

                        {#                        {% if std %}#}
                        {#                            <li><a href="{% url 'stdudent_dashboard' %}"><i class="mx-3 h3 bi bi-grid"></i> <span>Profil Student</span></a></li>#}
                        <li><a href="{% url 'account:stdudent_dashboard' %}"><i class="mx-3 h3 bi bi-grid"></i> <span>Profil Student</span></a>
                        </li>
                        <li>
                            {#                                <a href="{% url 'student_course_list' %}"><i class="mx-3 h3 bi bi-mortarboard-fill"></i><span>Mening kurslarim</span>#}
                            <a href="{% url 'account:student_course_list' %}"><i
                                    class="mx-3 h3 bi bi-mortarboard-fill"></i><span>Mening kurslarim</span>
                            </a>
                        </li>
                        {#                        {% endif %}#}


                        <li>
                            <a href="{% url 'account:log_out' %}"><i class="mx-3 bi bi-box-arrow-left"></i></span><span>Chiqish</span>
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav><!-- .navbar -->
        {% comment %} <a href="#about" class="get-started-btn scrollto"> <i class="bi bi-box-arrow-right"></i>Get Started</a> {% endcomment %}
    </div>
</header><!-- End Header -->

courses/templates/course/include/_hero.html
{% load static %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">

    <div class="container" data-aos="zoom-out" data-aos-delay="100">
        <div class="row">
            <div class="col-xl-6">
                <h1>Professionallar va umrbod ta'lim</h1>
                <h2>Yorqin kelajak uchun ko'nikmalar. Biz bilan boshlang.</h2>
                <a href="{% url 'course:course_list' %}" class="btn-get-started scrollto">Boshlash</a>
            </div>
        </div>
    </div>

</section>
<!-- End Hero -->

courses/templates/course/include/courses__header.html
{% load static %}
<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

        <h1 class="logo me-auto"><a href="index.html">Mentor</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

        <nav id="navbar" class="navbar order-last order-lg-0">
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="about.html">About</a></li>
                <li><a class="active" href="courses.html">Courses</a></li>
                <li><a href="trainers.html">Trainers</a></li>
                <li><a href="events.html">Events</a></li>
                <li><a href="pricing.html">Pricing</a></li>

                <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
                    <ul>
                        <li><a href="#">Drop Down 1</a></li>
                        <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                            <ul>
                                <li><a href="#">Deep Drop Down 1</a></li>
                                <li><a href="#">Deep Drop Down 2</a></li>
                                <li><a href="#">Deep Drop Down 3</a></li>
                                <li><a href="#">Deep Drop Down 4</a></li>
                                <li><a href="#">Deep Drop Down 5</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Drop Down 2</a></li>
                        <li><a href="#">Drop Down 3</a></li>
                        <li><a href="#">Drop Down 4</a></li>
                    </ul>
                </li>
                <li><a href="contact.html">Contact</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

        <a href="courses.html" class="get-started-btn">Get Started</a>

    </div>
</header><!-- End Header -->